-- Add household_measure to coach_food_serves for scale-free portioning
ALTER TABLE coach_food_serves ADD COLUMN IF NOT EXISTS household_measure text;

-- Pre-populate for all existing foods
UPDATE coach_food_serves SET household_measure = CASE food_name
  -- ── Proteins ──────────────────────────────────────────────────────────────
  WHEN 'Chicken breast, raw'      THEN '1 palm'
  WHEN 'Tuna in springwater'      THEN '½ cup'
  WHEN 'Basa fillet, raw'         THEN '1 palm'
  WHEN 'Pork, lean raw'           THEN '1 palm'
  WHEN 'Egg whites'               THEN '1¼ cups'
  WHEN 'Protein powder'           THEN '1 scoop'
  WHEN 'Salmon, raw'              THEN '1 palm'
  WHEN 'Chicken thigh, raw'       THEN '1 palm'
  WHEN 'Barramundi, raw'          THEN '1 palm'
  WHEN 'Whole eggs'               THEN '2 eggs'
  WHEN 'Tempeh'                   THEN '⅔ cup'
  WHEN 'Tofu, firm'               THEN '1¼ cups'
  WHEN 'Brown lentils, cooked'    THEN '¾ cup'
  WHEN 'Edamame beans'            THEN '1 cup'
  WHEN 'Chickpeas, canned'        THEN '½ cup'
  -- ── Carbs ─────────────────────────────────────────────────────────────────
  WHEN 'Jasmine rice, raw'        THEN '¼ cup raw'
  WHEN 'Jasmine rice, cooked'     THEN '⅓ cup'
  WHEN 'Brown rice, raw'          THEN '¼ cup raw'
  WHEN 'Brown rice, cooked'       THEN '⅓ cup'
  WHEN 'Rolled oats'              THEN '⅓ cup'
  WHEN 'Pasta, raw'               THEN 'small handful'
  WHEN 'Pasta, cooked'            THEN '½ cup'
  WHEN 'Sourdough bread'          THEN '1–2 slices'
  WHEN 'Wholegrain bread'         THEN '1–2 slices'
  WHEN 'Sweet potato, raw'        THEN '1 medium'
  WHEN 'White potato, raw'        THEN '1 medium'
  WHEN 'Butternut pumpkin, raw'   THEN '2 fists'
  WHEN 'Weetbix'                  THEN '2 biscuits'
  WHEN 'Muesli / granola'         THEN '¼ cup'
  -- ── Fats — Seeds ──────────────────────────────────────────────────────────
  WHEN 'Sunflower seeds'          THEN '2 tbsp'
  WHEN 'Pumpkin seeds (pepitas)'  THEN '2 tbsp'
  WHEN 'Linseed / flaxseed'       THEN '2 tbsp'
  WHEN 'Chia seeds'               THEN '2 tbsp'
  WHEN 'Sesame seeds'             THEN '1 tbsp'
  WHEN 'Hemp seeds'               THEN '2 tbsp'
  -- ── Fats — Nuts ───────────────────────────────────────────────────────────
  WHEN 'Almonds'                  THEN '~16 nuts'
  WHEN 'Walnuts'                  THEN '~7 halves'
  WHEN 'Macadamia nuts'           THEN '~5 nuts'
  WHEN 'Cashews'                  THEN '~14 nuts'
  WHEN 'Pecans'                   THEN '~8 halves'
  WHEN 'Brazil nuts'              THEN '~3 nuts'
  WHEN 'Pistachios'               THEN '~45 nuts'
  -- ── Fats — Nut Butters ────────────────────────────────────────────────────
  WHEN 'Peanut butter'            THEN '1 tbsp'
  WHEN 'Almond butter'            THEN '1 tbsp'
  WHEN 'Cashew butter'            THEN '1 tbsp'
  -- ── Fats — Oils ───────────────────────────────────────────────────────────
  WHEN 'Extra virgin olive oil'   THEN '1 tbsp'
  WHEN 'Coconut oil'              THEN '1 tbsp'
  WHEN 'Avocado oil'              THEN '1 tbsp'
  -- ── Fats — Other ──────────────────────────────────────────────────────────
  WHEN 'Avocado (Hass)'           THEN '½ medium'
  WHEN 'Pesto'                    THEN '2 tbsp'
  WHEN 'Tahini'                   THEN '1 tbsp'
  WHEN 'Coconut milk (tin)'       THEN '¼ cup'
  WHEN 'Dark chocolate 85%'       THEN '4 squares'
  -- ── Fats — Cheese ─────────────────────────────────────────────────────────
  WHEN 'Tasty cheese'             THEN '6 small cubes'
  WHEN 'Brie cheese'              THEN '2 slices'
  WHEN 'Feta cheese'              THEN '4 cubes'
  WHEN 'Parmesan'                 THEN '2 tbsp grated'
  -- ── Fruit ─────────────────────────────────────────────────────────────────
  WHEN 'Apple, red'               THEN '1 medium'
  WHEN 'Apple, green'             THEN '1 medium'
  WHEN 'Banana'                   THEN '1 medium'
  WHEN 'Pineapple'                THEN '1¾ cups'
  WHEN 'Mango'                    THEN '1 cup sliced'
  WHEN 'Strawberries'             THEN '~2 cups'
  WHEN 'Raspberries'              THEN '~2 cups'
  WHEN 'Papaya'                   THEN '1¼ cups'
  WHEN 'Rockmelon'                THEN '2 cups'
  WHEN 'Watermelon'               THEN '1½ cups'
  WHEN 'Kiwifruit'                THEN '2 medium'
  WHEN 'Grapes'                   THEN '~1 cup'
  WHEN 'Peach'                    THEN '1 large'
  WHEN 'Pear'                     THEN '1 medium'
  WHEN 'Orange'                   THEN '1 large'
  WHEN 'Mandarin'                 THEN '2 medium'
  WHEN 'Blueberries'              THEN '1¼ cups'
  -- ── Condiments — fat ──────────────────────────────────────────────────────
  WHEN 'Garlic aioli'             THEN '2 tbsp'
  WHEN 'Creamy mayonnaise'        THEN '1 tbsp'
  WHEN 'Ranch dressing'           THEN '2 tbsp'
  WHEN 'Caesar dressing'          THEN '2 tbsp'
  WHEN 'Balsamic dressing'        THEN '3 tbsp'
  WHEN 'Kewpie mayonnaise'        THEN '1 tbsp'
  WHEN 'Japanese sesame dressing' THEN '3 tbsp'
  WHEN 'Tahini dressing'          THEN '1 tbsp'
  -- ── Condiments — carb ─────────────────────────────────────────────────────
  WHEN 'Tomato sauce'             THEN '4 tbsp'
  WHEN 'BBQ sauce'                THEN '3 tbsp'
  WHEN 'Sweet chilli sauce'       THEN '3 tbsp'
  WHEN 'Honey'                    THEN '1 tbsp'
  WHEN 'Kecap manis (sweet soy)'  THEN '2 tbsp'
  WHEN 'Teriyaki sauce'           THEN '3 tbsp'
  WHEN 'Hoisin sauce'             THEN '2 tbsp'
  -- ── Free condiments ───────────────────────────────────────────────────────
  WHEN 'Vegemite'                 THEN '½ tsp'
  ELSE household_measure
END
WHERE household_measure IS NULL OR household_measure = '';
